#!/usr/bin/sh

startOnce() {
	[ pidof "$1" ] || "$@" &
	sleep 0.3s
}

# do bspc rule --add $window state=floating follow=on desktop=Number

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 2
bspc config window_gap 6

bspc config split_ratio 0.5

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config focus_follows_pointer false

bspc config normal_border_color "#6e6a86"
bspc config focused_border_color "#c4a7e7"
bspc config active_border_color "#eb6f92"

wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
export SXHKD_SHELL=sh

#### autostart applications
startOnce sxhkd
startOnce polybar
libinput-gestures-setup >/dev/null && libinput-gestures-setup start

[pidof xfsettingsd] && (sleep 20 && killall xfsettingsd)
